Fix: The `beta` docker image was used only for `chown`
aleph-im/pyaleph pull request #189
Opened 2022-02-22 13:27 UTC by hoh

Solution: Use the current release tag instead.

2022-02-22 13:36 UTC, odesenfans requested changes

2022-02-22 13:36 UTC, odesenfans commented on docs/guides/install.rst
>  .. code-block:: bash
Change to parsed-literal.

2022-02-22 13:36 UTC, odesenfans commented on docs/guides/upgrade.rst
> +    docker run --rm -ti --user root -v $(pwd)/keys:/opt/pyaleph/keys alephim/pyaleph-node:|pyaleph_version| chown aleph:aleph /opt/pyaleph/keys
Change to parsed-literal.

2022-02-28 09:27 UTC, odesenfans approved these changes

2022-02-28 09:29 UTC, hoh commented
Fixed and rebased

2022-02-28 10:03 UTC, merged