hoh fix command
aleph-im/pyaleph pull request #394
Opened 2023-04-14 14:31 UTC by hoh

- Feature: support Micheline-style signatures for Tezos (#330)
- Internal: improve validation of the aggregates endpoint (#341)
- Internal: store the full TX context in confirmations (#265)
- more rebase fixes
- Feature: return errors for invalid message API queries (#335)
- Fix: refuse time and pagination parameters for message WS
- Fix: reactivate message API time filters (#345)
- Feature: return errors for invalid post API queries (#344)
- Fix: parse refs and hashes fields correctly for messages API (#346)
- Internal: OO services
- Feature: use the file system to store files
- Feature: switch to Postgres
- Feature: support multiple addresses for balance posts
- Fix: stop logging exception on invalid AVAX signature
- Feature: publish all processed messages on RabbitMQ
- Feature: POST /messages/ endpoint
- Fix: catch BadSignatureError in Cosmos signature verification
- Fix: remove unused large fixtures for balance tests
- Fix: respect `types` filter in /posts.json
- Fix: re-enable filtering on content["type"] for /messages
- Feature: sort messages and posts by confirmation time
- Fix: forget posts with amends
- Feature: program version table
- Feature: exponential message retry times
- Chore: bump aleph-message to 0.3.0
- Feature: balance views
- Fix: only one row per address in costs view
- Feature: Python 3.11 support
- Feature: run tests on the real DB setup
- Internal: test error code enum values
- Fix: internal error on invalid message time fields
- Feature: use orjson as JSON parser
- Feature: Tezos message sync
- Feature: support all message types in smart contract protocol
- Fix: forget aggregates
- Feature: /addresses/{address}/files endpoint
- Chore: use Tezos mainnet indexer as default
- Fix: use `seen_ids` only for off-chain sync txs
- Chore: update aleph-message
- Fix: do not generate null fields when processing STORE_IPFS
- Fix: 500 on /messages for messages without signature
- Fix: multiple Tezos indexer sync issues
- Fix: default data storage folder
- Feature: performance monitoring with Sentry (#376)
- Fix: slow response times on addresses/stats.json (#377)
- Internal: remove dead code
- Feature: support all message types for chain txs
- Feature: table count estimates
- Temporary: more performance analytics for API server
- Internal: support sync and message chain sync statuses
- Feature: fetch message/sync events from the Aleph indexer
- Fix: avoid Sentry exceptions with websockets
- Fix: support tags in /messages.json
- Fix: improve performance of /messages/ for large queries
- Fix: rename /posts/ owner field to address
- Fix: /v0/posts is now backwards compatible
- Fix: wait for P2P service at startup
- Fix: commit address materialized view refresh
- Release candidate: v0.5.0-rc1
- Fix: reduce total log files size (#387)
- Internal: import libp2p stubs from p2pclient (#390)
- Internal: replace Python shared memory by Redis (#391)
- Fix: restrict storage endpoints to files stored on aleph.im
- Fix: download large IPFS files gracefully
- Fix: return 413 on /storage/ for files larger than 100MB
- Internal: lazy check if IPFS is enabled in storage code
- Internal: make file size column not nullable
- Feature: separate API process (#393)
- Release candidate: v0.5.0-rc2
- Fix: Docker compose command did not make sense on this entrypoint

2023-04-16 14:09 UTC, odesenfans requested changes

2023-04-16 14:09 UTC, odesenfans commented on deployment/samples/docker-compose/docker-compose.yml
> -    command: --config /opt/pyaleph/config.yml --key-dir /opt/pyaleph/keys -v
`--config` is still required.

2023-04-17 13:50 UTC, hoh commented on deployment/samples/docker-compose/docker-compose.yml
> -    command: --config /opt/pyaleph/config.yml --key-dir /opt/pyaleph/keys -v
Fixed

2023-04-17 13:51 UTC, odesenfans approved these changes

2023-04-17 14:43 UTC, merged