Fix: Old method upload
aleph-im/pyaleph pull request #535
Opened 2023-12-19 10:57 UTC by 1yam

Problem:
We require the old upload method to remain functional. In some cases, it may crash due to the HTTP client not setting the multipart header for the file_field.

Solution:
If no message is sent, we don't need to know the file size. We can simply read chunks until we reach the maximum size for unauthenticated uploads.

2023-12-19 12:31 UTC, MHHukiewitz requested changes
Needs a bit of work. Also, some tests checking the failure states (too big file, Content-Length mismatch) should be included.

2023-12-19 12:31 UTC, MHHukiewitz commented on src/aleph/web/controllers/storage.py
> +        )
This attribute doesn't seem to be used

2023-12-19 12:31 UTC, MHHukiewitz commented on src/aleph/web/controllers/storage.py
> +                self._content = self.file_field.file.read()
This should use `self.read_file_with_max_size()` and possibly throw an exception, if we were not able to read everything

2023-12-19 12:31 UTC, MHHukiewitz commented on src/aleph/web/controllers/storage.py
> +                raise web.HTTPForbidden()
Throw `413 Payload Too Large` instead. Throw `400 Bad Request` if Content-Length does not match actual body bytes.

2023-12-20 16:04 UTC, MHHukiewitz approved these changes
LGTM

2023-12-21 09:49 UTC, MHHukiewitz requested changes
After doing some research, I discovered that `await request.post()` reads the WHOLE request body into memory, clearly defeating the purpose of much of the code here.

2024-02-29 12:03 UTC, nesitor commented
Closed in favour https://github.com/aleph-im/pyaleph/pull/559

2024-02-29 12:03 UTC, closed without merging